# Generated by Django 3.2.5 on 2022-05-26 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_comen', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=50)),
                ('comentarios', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('titulo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sub_titulo', models.CharField(max_length=50, null=True)),
                ('cuerpo', models.CharField(max_length=3000)),
                ('monto_meta', models.FloatField(null=True)),
                ('monto_recauda', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_proyecto2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_solicitud',
            fields=[
                ('id_Cat_sol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50, null=True)),
                ('apellidos_pat', models.CharField(max_length=50, null=True)),
                ('apellido_mat', models.CharField(max_length=50, null=True)),
                ('correo', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transsaccion',
            fields=[
                ('id_Trans', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('monto', models.FloatField()),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestion.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_proyecto',
            fields=[
                ('id_tipo_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestion.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id_solicitudes', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='solicitudes/', verbose_name='Imagen')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto2',
            fields=[
                ('titulo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('sub_titulo', models.CharField(max_length=50, null=True)),
                ('cuerpo', models.CharField(max_length=3000)),
                ('monto_meta', models.FloatField(null=True)),
                ('monto_recauda', models.FloatField(null=True)),
                ('nombre_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestion.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=50)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Material_pro',
            fields=[
                ('id_mat', models.AutoField(primary_key=True, serialize=False)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='materiales/', verbose_name='Imagen')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='materiales/', verbose_name='Imagen')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='materiales/', verbose_name='Imagen')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='materiales/', verbose_name='Imagen')),
                ('foto5', models.ImageField(blank=True, null=True, upload_to='materiales/', verbose_name='Imagen')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestion.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo_pro',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=50)),
                ('cargo1', models.CharField(max_length=50)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Imagen')),
                ('nombre2', models.CharField(max_length=50)),
                ('cargo2', models.CharField(max_length=50)),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Imagen')),
                ('nombre3', models.CharField(max_length=50)),
                ('cargo3', models.CharField(max_length=50)),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Imagen')),
                ('nombre4', models.CharField(max_length=50)),
                ('cargo4', models.CharField(max_length=50)),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Imagen')),
                ('nombre5', models.CharField(max_length=50)),
                ('cargo5', models.CharField(max_length=50)),
                ('foto5', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Imagen')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestion.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Datos_banco',
            fields=[
                ('id_banco', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_banco', models.CharField(max_length=50)),
                ('cuenta_bancaria', models.IntegerField()),
                ('rut', models.CharField(max_length=50)),
                ('tipo_cuenta', models.CharField(max_length=50)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=50)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestion.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Benefio_pro',
            fields=[
                ('id_benef', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_benef', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestion.proyecto')),
            ],
        ),
    ]
