# Generated by Django 4.0.5 on 2022-06-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True),
        ),
    ]
