# Generated by Django 4.0.5 on 2022-06-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0002_categoria_alter_projecto5_categoria_delete_tipos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecto5',
            name='categoria',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
