# Generated by Django 4.0.5 on 2022-06-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0005_datos_usuario_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_banco',
            name='tipo_cuenta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='datos_banco',
            name='tipo_tarjeta',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
