# Generated by Django 4.0.5 on 2022-06-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0006_datos_banco_tipo_cuenta_datos_banco_tipo_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_banco',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos_banco',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos_banco',
            name='rut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos_banco',
            name='tarjeta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos_banco',
            name='tipo_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datos_banco',
            name='tipo_tarjeta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
