# Generated by Django 4.0.5 on 2022-06-20 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0009_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='tipo_cuenta',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='tipo_tarjeta',
        ),
    ]
