# Generated by Django 4.0.5 on 2022-07-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0013_comunicaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_usuario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
