# Generated by Django 4.0.4 on 2022-04-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dato', models.CharField(max_length=50)),
            ],
        ),
    ]
