# Generated by Django 4.0.4 on 2022-05-05 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0003_remove_prueba_id_alter_prueba_dato'),
    ]

    operations = [
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ciudad', models.CharField(max_length=50)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestion.pais')),
            ],
        ),
    ]
