# Generated by Django 4.0.4 on 2022-05-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0004_pais_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id_comen', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=50)),
                ('comentarios', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos_pat', models.CharField(max_length=50)),
                ('apellido_mat', models.CharField(max_length=50, null=True)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=12, null=True)),
                ('roll', models.IntegerField(default=1)),
            ],
        ),
    ]
