# Generated by Django 4.0.4 on 2022-05-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0005_contacto_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='datos_banco',
            fields=[
                ('id_banco', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_banco', models.CharField(max_length=50)),
                ('cuenta_bancaria', models.IntegerField()),
                ('rut', models.CharField(max_length=50)),
                ('tipo_cuenta', models.CharField(max_length=50)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appgestion.usuarios')),
            ],
        ),
    ]
