# Generated by Django 4.0.4 on 2022-05-07 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0006_datos_banco'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitudes',
            fields=[
                ('id_solicitudes', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('upload', models.FileField(upload_to='uploads')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestion.pais')),
            ],
        ),
    ]
