# Generated by Django 4.0.4 on 2022-05-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0007_solicitudes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudes',
            name='upload',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
