# Generated by Django 4.0.4 on 2022-05-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0008_alter_solicitudes_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes',
            name='upload',
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='solicitudes', verbose_name='Imagen'),
        ),
    ]
