# Generated by Django 4.0.4 on 2022-05-07 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0009_remove_solicitudes_upload_solicitudes_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_solicitud',
            fields=[
                ('id_Cat_sol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cat', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='solicitudes/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appgestion.usuarios'),
        ),
    ]
