# Generated by Django 4.0.4 on 2022-05-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0010_tipo_solicitud_alter_solicitudes_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('sub_titulo', models.CharField(max_length=50, null=True)),
                ('cuerpo', models.CharField(max_length=3000)),
                ('monto_meta', models.IntegerField(null=True)),
                ('monto_recauda', models.IntegerField(null=True)),
            ],
        ),
    ]
