# Generated by Django 4.0.4 on 2022-05-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0011_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='benefio_pro',
            fields=[
                ('id_benef', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_benef', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='equipo_pro',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre1', models.CharField(max_length=50)),
                ('cargo1', models.CharField(max_length=50)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Imagen')),
                ('nombre2', models.CharField(max_length=50)),
                ('cargo2', models.CharField(max_length=50)),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Imagen')),
                ('nombre3', models.CharField(max_length=50)),
                ('cargo3', models.CharField(max_length=50)),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Imagen')),
                ('nombre4', models.CharField(max_length=50)),
                ('cargo4', models.CharField(max_length=50)),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Imagen')),
                ('nombre5', models.CharField(max_length=50)),
                ('cargo5', models.CharField(max_length=50)),
                ('foto5', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='material_pro',
            fields=[
                ('id_mat', models.AutoField(primary_key=True, serialize=False)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='materiales/', verbose_name='Imagen')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='materiales/', verbose_name='Imagen')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='materiales/', verbose_name='Imagen')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='materiales/', verbose_name='Imagen')),
                ('foto5', models.ImageField(blank=True, null=True, upload_to='materiales/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_proyecto',
            fields=[
                ('id_tipo_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='transsaccion',
            fields=[
                ('id_Trans', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('monto', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='monto_meta',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='monto_recauda',
            field=models.FloatField(null=True),
        ),
    ]
