# Generated by Django 4.0.4 on 2022-06-10 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_comen', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=50)),
                ('comentarios', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos',
            fields=[
                ('categoria', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projecto5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('contenido', froala_editor.fields.FroalaField()),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True)),
                ('imagen', models.ImageField(upload_to='media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload_to', models.DateTimeField(auto_now=True)),
                ('monto_meta', models.IntegerField()),
                ('monto_total', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appgestion.tipos')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('paginaWeb', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appgestion.projecto5')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50, null=True)),
                ('descripcion_empresa', models.CharField(blank=True, max_length=500)),
                ('nombre_jefeProjecto', models.CharField(blank=True, max_length=50)),
                ('nombre_subjefe', models.CharField(blank=True, max_length=50)),
                ('nombre_subSubjefe', models.CharField(blank=True, max_length=50)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appgestion.projecto5')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_beneficio', models.CharField(max_length=50)),
                ('nombre_beneficio', models.CharField(max_length=50)),
                ('descripcion_beneficio', models.CharField(max_length=5000)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appgestion.projecto5')),
            ],
        ),
    ]
