# Generated by Django 4.0.5 on 2022-06-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appgestion', '0004_datos_usuario_datos_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_usuario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
